/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>


#ifndef _Included_com_phone_ndkdemo_JNITest
#define _Included_com_phone_ndkdemo_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_phone_ndkdemo_JNITest
 * Method:    get
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_phone_ndkdemo_JNITest_get
  (JNIEnv *, jclass);


#ifdef __cplusplus
}
#endif
#endif
